### ISSUE TITLE
Bootloop on Android 14 Kernel 4.14.343

### ISSUE THREAD

**Issue by denizsafak** [Magisk-Modules-Alt-Repo/drc-remover#2]
When I flash it with Magisk, I goes into bootloop (stucks in loading screen)

Phone: Xiaomi Mi 11 Lite 4G (courbet)
Android Verison: 14.0.0_r35
Kernel: 4.14.343-openela-AlfaKernel
Security Update: May 5, 2024
Baseband Version: SS.AT.4.3.c5-00165-SM6150_GEN_PACK-1.35003.10
Build Number: AP1A.240505.005 release-keys

It happened to me in EvolutionX, AlphaDroid and LineageOS roms. They all use the same kernels. Had to remove the module manually, using OrangeFox recovery. (My bootloop protector module was enabled)

I believe there is an issue with the newest kernel. Thanks for help!

Edit: I installed CRDroid 10.5, still has the same issue. There were no issues in version 10.4. Please fix.

**Comment by yzyhk904** [comment]
There isn't such thing in this module.  It changes "/vendor/etc/audio_policy_configuration.xml" only.
Perhaps, the cause came from other modules or new ROM.

**Comment by denizsafak** [comment]
> There isn't such thing in this module. It changes "/vendor/etc/audio_policy_configuration.xml" only. Perhaps, the cause came from other modules or new ROM.

You are right, it might be related to rom. Some rom publishers include KernelSU by default. Can this module cause bootloop when both Magisk and KernelSU are installed? I tried another rom without KernelSU and problem solved. But still not sure what causes it.

(Courbet, LineageOS 21, 4.14.190-perf)

**Comment by yzyhk904** [comment]
It hasn't been causing bootloop on KernelSU and official Magisk's. I've heard that non-official Magisk's caused some issues.

Don't you use incompatible Magisk alpha or Kitsune?
