### ISSUE TITLE
Cannot install on normal Magisk

### ISSUE THREAD

**Issue by dtrail** [Magisk-Modules-Alt-Repo/drc-remover#3]
It tells me, that it would be aborted "by no Magisk-Mirrors".
So, it's official Magisk 27, that I'm using.

**Comment by yzyhk904** [comment]
Sorry for late reply. 

Probably you are using a canary version. It isn't officially released. Use the latest released version! It's official.

**Comment by dtrail** [comment]
I had the same issue, wwhen I attempted to install one of your modules on officially releases Magisk 28.

**Comment by yzyhk904** [comment]
Magisk v28.0 isn't backward compatible. It lacks a very important feature that enables correct module updating. Module developers are baffled with Magisk v28.0. I'll ignore Magisk v28.0 and am hoping v28.1 to recover backward compatibility.

Please stay using Magisk v27.0 or use "Compatible Magisk-mirroring" to patch Magisk v28.0 for correct module updating.

**Comment by dtrail** [comment]
Oh, that explains some issues I recently had. So far I was able to circumvent them by installing one module manually.. But it's good to know the real reason.

**Comment by yzyhk904** [comment]
I've been distributing a Magisk module to patch Official Magisk v28.0, KernelSU, and other variants for installing pure pre-v28.0 Magisk modules including my modules for months. See [Compatible Magisk-mirroring](https://github.com/Magisk-Modules-Alt-Repo/compatible-magisk-mirroring).
